server:
  port: 8081

spring:
  application:
    name: eureka-hello

info:
  app:
    name: spring-boot-actuator
    version: 1.0.0
    test: test

eureka:
  client:
    serviceUrl:
       defaultZone: http://localhost:8080/eureka/

management:
  endpoints:
    web:
     exposure:
       include: '*'
  endpoint:
    health:
      show-details: always
    shutdown:
      enabled: true