server:
  port: 8082

spring:
  application:
    name: server-ribbon

eureka:
  client:
    serviceUrl:
       defaultZone: http://localhost:8080/eureka/

management:
  endpoints:
    web:
     exposure:
       include: '*'
  endpoint:
    health:
      show-details: always
    shutdown:
      enabled: true